title: BTW Podcast
description: Initiates hashing stuff out
author: WitchfulThoughts
email: 
lang: en-uk
copyright: "&#x2117; &amp; &#xA9; 2020"
logo: /assets/img/logo.png
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
